name: Remove blacklisted entries from manifest.txt

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ github.token }}
    - name: Backup vim-plugins.nix # TODO: workaround: if vim-plugins is broken, all 'nix run' actions will fail
      shell: bash
      run: |
        mv ./pkgs/vim-plugins.nix ./pkgs/vim-plugins.nix.bak
        echo "{ ...} : {}" > ./pkgs/vim-plugins.nix
    - name: Generate derivations for new plugins
      shell: bash
      run: |
        nix run .#update-vim-plugins -- cleanup
    - name: Restore vim-plugins.nix
      shell: bash
      run: |
        mv ./pkgs/vim-plugins.nix.bak ./pkgs/vim-plugins.nix
